### ISSUE TITLE
ツイートの複数送信について

### ISSUE THREAD

**Issue by Okazuki** [chomado/chomado_bot#37]
初めまして。こちらのgithubを参考にさせて頂き現在phpでtwitterbotを作成している者です。
TwitterUtil.phpにて時間をおいて最大3回ツイートを試行している理由を教えて頂きたいです。

**Comment by fetus-hina** [comment]
リモートプロシージャの呼び出しは当然ながら失敗します。
（ネットワーク的要因、リモートサーバ内の要因）

失敗したときにたまたま状態が悪かった可能性は高いので、3回連続で試行しています。

何かに3回試行しろと書いてあったためデフォルトがそうなっていると記憶していますが、
現在のところその文章を見つけられていません。

**Comment by strpOkazaki** [comment]
返信ありがとうございます。

何らかの要因で一回で成功しなかった時のために数回思考する感じですかね。
参考にさせて頂きます。ありがとうございました。

**Comment by Okazuki** [comment]
返信ありがとうございました。
参考にさせて頂きます。
